[
    {
        "content": "<p>jlb6740 opened <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823\">issue #10823</a>:</p>\n<blockquote>\n<p>@alexcrichton @abrown </p>\n<blockquote>\n<p>Testing in the new assembler fails when no capture is passed --nocapture <br>\ncd cranelift/assembler-x64<br>\ncargo test -- --nocapture</p>\n</blockquote>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"n\">Test</span><span class=\"w\"> </span><span class=\"n\">executable</span><span class=\"w\"> </span><span class=\"n\">failed</span><span class=\"w\"> </span><span class=\"p\">(</span><span class=\"n\">exit</span><span class=\"w\"> </span><span class=\"n\">status</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"mi\">101</span><span class=\"p\">).</span>\n\n<span class=\"n\">stderr</span><span class=\"p\">:</span>\n\n<span class=\"nc\">thread</span><span class=\"w\"> </span><span class=\"o\">'</span><span class=\"na\">main</span><span class=\"o\">'</span><span class=\"w\"> </span><span class=\"n\">panicked</span><span class=\"w\"> </span><span class=\"n\">at</span><span class=\"w\"> </span><span class=\"o\">/</span><span class=\"n\">home</span><span class=\"o\">/</span><span class=\"n\">jlbirch</span><span class=\"o\">/</span><span class=\"n\">wasmtime</span><span class=\"o\">-</span><span class=\"n\">jlb6740</span><span class=\"o\">-</span><span class=\"k\">for</span><span class=\"o\">-</span><span class=\"n\">assembler</span><span class=\"o\">-</span><span class=\"n\">dev</span><span class=\"o\">/</span><span class=\"n\">cranelift</span><span class=\"o\">/</span><span class=\"n\">assembler</span><span class=\"o\">-</span><span class=\"n\">x64</span><span class=\"o\">/</span><span class=\"n\">src</span><span class=\"o\">/</span><span class=\"n\">fixed</span><span class=\"p\">.</span><span class=\"n\">rs</span><span class=\"p\">:</span><span class=\"mi\">45</span><span class=\"p\">:</span><span class=\"mi\">9</span><span class=\"p\">:</span>\n<span class=\"nc\">assertion</span><span class=\"w\"> </span><span class=\"n\">failed</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"nc\">self</span><span class=\"p\">.</span><span class=\"mf\">0.</span><span class=\"n\">enc</span><span class=\"p\">()</span><span class=\"w\"> </span><span class=\"o\">==</span><span class=\"w\"> </span><span class=\"n\">E</span>\n<span class=\"n\">note</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"nc\">run</span><span class=\"w\"> </span><span class=\"n\">with</span><span class=\"w\"> </span><span class=\"err\">`</span><span class=\"n\">RUST_BACKTRACE</span><span class=\"o\">=</span><span class=\"mi\">1</span><span class=\"err\">`</span><span class=\"w\"> </span><span class=\"n\">environment</span><span class=\"w\"> </span><span class=\"n\">variable</span><span class=\"w\"> </span><span class=\"n\">to</span><span class=\"w\"> </span><span class=\"n\">display</span><span class=\"w\"> </span><span class=\"n\">a</span><span class=\"w\"> </span><span class=\"n\">backtrace</span>\n</code></pre></div>\n<p>I tracked down that the error started occurring after this patch was merged:<br>\n<a href=\"https://github.com/bytecodealliance/wasmtime/pull/10806\">https://github.com/bytecodealliance/wasmtime/pull/10806</a></p>\n<p>Note, there is no assertion error when the </p>\n<blockquote>\n<p>--nocapture</p>\n</blockquote>\n<p>option is omitted. </p>\n</blockquote>",
        "id": 519738161,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1747883446
    },
    {
        "content": "<p>alexcrichton <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823#issuecomment-2901461205\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823\">issue #10823</a>:</p>\n<blockquote>\n<p>I think you're seeing the output of <a href=\"https://github.com/bytecodealliance/wasmtime/blob/66754e245ce04d6624c52e9a073f4510bb30c3b1/cranelift/assembler-x64/src/fixed.rs#L19-L24\">this test</a> which is supposed to panic. Is this failing tests for you locally? While <code>--nocapture</code> shows the message the exit code of <code>cargo test -- --nocapture</code> is still 0 for me</p>\n</blockquote>",
        "id": 519851062,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1747924342
    },
    {
        "content": "<p>jlb6740 closed <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823\">issue #10823</a>:</p>\n<blockquote>\n<p>@alexcrichton @abrown </p>\n<blockquote>\n<p>Testing in the new assembler fails when no capture is passed --nocapture <br>\ncd cranelift/assembler-x64<br>\ncargo test -- --nocapture</p>\n</blockquote>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"n\">Test</span><span class=\"w\"> </span><span class=\"n\">executable</span><span class=\"w\"> </span><span class=\"n\">failed</span><span class=\"w\"> </span><span class=\"p\">(</span><span class=\"n\">exit</span><span class=\"w\"> </span><span class=\"n\">status</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"mi\">101</span><span class=\"p\">).</span>\n\n<span class=\"n\">stderr</span><span class=\"p\">:</span>\n\n<span class=\"nc\">thread</span><span class=\"w\"> </span><span class=\"o\">'</span><span class=\"na\">main</span><span class=\"o\">'</span><span class=\"w\"> </span><span class=\"n\">panicked</span><span class=\"w\"> </span><span class=\"n\">at</span><span class=\"w\"> </span><span class=\"o\">/</span><span class=\"n\">home</span><span class=\"o\">/</span><span class=\"n\">jlbirch</span><span class=\"o\">/</span><span class=\"n\">wasmtime</span><span class=\"o\">-</span><span class=\"n\">jlb6740</span><span class=\"o\">-</span><span class=\"k\">for</span><span class=\"o\">-</span><span class=\"n\">assembler</span><span class=\"o\">-</span><span class=\"n\">dev</span><span class=\"o\">/</span><span class=\"n\">cranelift</span><span class=\"o\">/</span><span class=\"n\">assembler</span><span class=\"o\">-</span><span class=\"n\">x64</span><span class=\"o\">/</span><span class=\"n\">src</span><span class=\"o\">/</span><span class=\"n\">fixed</span><span class=\"p\">.</span><span class=\"n\">rs</span><span class=\"p\">:</span><span class=\"mi\">45</span><span class=\"p\">:</span><span class=\"mi\">9</span><span class=\"p\">:</span>\n<span class=\"nc\">assertion</span><span class=\"w\"> </span><span class=\"n\">failed</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"nc\">self</span><span class=\"p\">.</span><span class=\"mf\">0.</span><span class=\"n\">enc</span><span class=\"p\">()</span><span class=\"w\"> </span><span class=\"o\">==</span><span class=\"w\"> </span><span class=\"n\">E</span>\n<span class=\"n\">note</span><span class=\"p\">:</span><span class=\"w\"> </span><span class=\"nc\">run</span><span class=\"w\"> </span><span class=\"n\">with</span><span class=\"w\"> </span><span class=\"err\">`</span><span class=\"n\">RUST_BACKTRACE</span><span class=\"o\">=</span><span class=\"mi\">1</span><span class=\"err\">`</span><span class=\"w\"> </span><span class=\"n\">environment</span><span class=\"w\"> </span><span class=\"n\">variable</span><span class=\"w\"> </span><span class=\"n\">to</span><span class=\"w\"> </span><span class=\"n\">display</span><span class=\"w\"> </span><span class=\"n\">a</span><span class=\"w\"> </span><span class=\"n\">backtrace</span>\n</code></pre></div>\n<p>I tracked down that the error started occurring after this patch was merged:<br>\n<a href=\"https://github.com/bytecodealliance/wasmtime/pull/10806\">https://github.com/bytecodealliance/wasmtime/pull/10806</a></p>\n<p>Note, there is no assertion error when the </p>\n<blockquote>\n<p>--nocapture</p>\n</blockquote>\n<p>option is omitted. </p>\n</blockquote>",
        "id": 519895394,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1747938023
    },
    {
        "content": "<p>jlb6740 <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823#issuecomment-2902167508\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823\">issue #10823</a>:</p>\n<blockquote>\n<p>@alexcrichton Looks like this is running the doctest you highlight and the test comments does say it should panic but this doc test is not new but the panic is (at least on my platform). Yes the exit code is still 0. I will close this. Perhaps the cargo update that had to do once I rebased against patch <a href=\"https://github.com/bytecodealliance/wasmtime/pull/10806\">https://github.com/bytecodealliance/wasmtime/pull/10806</a>, changed the behavior of this test for me. Will close. </p>\n</blockquote>",
        "id": 519895395,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1747938023
    },
    {
        "content": "<p>jlb6740 edited a <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823#issuecomment-2902167508\">comment</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823\">issue #10823</a>:</p>\n<blockquote>\n<p>@alexcrichton Looks like this is running the doctest you highlight and the test comments does say it should panic but the confusion for me was this doctest was not new, while the panic was (at least on my platform). Yes the exit code is still 0. Perhaps the cargo update that had to do once I rebased against patch <a href=\"https://github.com/bytecodealliance/wasmtime/pull/10806\">https://github.com/bytecodealliance/wasmtime/pull/10806</a>, changed the behavior of this test for me. I will close this.</p>\n</blockquote>",
        "id": 519895526,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1747938073
    },
    {
        "content": "<p>jlb6740 edited a <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823#issuecomment-2902167508\">comment</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10823\">issue #10823</a>:</p>\n<blockquote>\n<p>@alexcrichton Looks like this is running the doctest you highlight and the test comments does say it should panic but the confusion for me was this doctest was not new, while the panic was (at least on my platform). Yes the exit code is still 0. Perhaps the cargo update that had to be done once I rebased against patch <a href=\"https://github.com/bytecodealliance/wasmtime/pull/10806\">https://github.com/bytecodealliance/wasmtime/pull/10806</a>, changed the behavior of this test for me. I will close this.</p>\n</blockquote>",
        "id": 519896590,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1747938473
    }
]