<html>
<head><meta charset="utf-8"><title>WAMR · wamr · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://bytecodealliance.github.io/zulip-archive/stream/290350-wamr/index.html">wamr</a></h2>
<h3>Topic: <a href="https://bytecodealliance.github.io/zulip-archive/stream/290350-wamr/topic/WAMR.html">WAMR</a></h3>

<hr>

<base href="https://bytecodealliance.zulipchat.com">

<head><link href="https://bytecodealliance.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="509147997"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/290350-wamr/topic/WAMR/near/509147997" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Borja Tellado <a href="https://bytecodealliance.github.io/zulip-archive/stream/290350-wamr/topic/WAMR.html#509147997">(Mar 31 2025 at 09:38)</a>:</h4>
<p>"When working with WAMR and exceptions, is there any way to configure a callback (native function) to be triggered by WAMR whenever an exception in the WAMR domain occurs? I found <code>wasm_runtime_set_enlarge_mem_error_callback</code>, so I am looking for something similar but for any type of exception.</p>



<a name="509243627"></a>
<h4><a href="https://bytecodealliance.zulipchat.com#narrow/stream/290350-wamr/topic/WAMR/near/509243627" class="zl"><img src="https://bytecodealliance.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Notification Bot <a href="https://bytecodealliance.github.io/zulip-archive/stream/290350-wamr/topic/WAMR.html#509243627">(Mar 31 2025 at 16:01)</a>:</h4>
<p>This topic was moved here from <a class="stream-topic" data-stream-id="206238" href="/#narrow/channel/206238-general/topic/WAMR">#general &gt; WAMR</a> by <span class="user-mention silent" data-user-id="441103">David Bryant</span>.</p>



<hr><p>Last updated: Oct 25 2025 at 23:03 UTC</p>
</html>